cv/urls.py
# cv/urls.py
# -*- coding: UTF-8 -*-
from __future__ import unicode_literals
from django.conf.urls import patterns, url


urlpatterns = patterns('cv.views',
	url(r'^(?P<cv_id>\d+)/pdf/$', "download_cv_pdf", name="download_cv_pdf"),
)

locations/urls.py
# locations/urls.py
# -*- coding: UTF-8 -*-
from __future__ import unicode_literals
from django.conf.urls import url
from locations import views


urlpatterns = [
    url(r'^$', views.LocationListView.as_view(), name='location-list'),
    url(r'^(?P<slug>[^/]+)$', views.LocationDetailView.as_view(), name='location-detail'),
    url(r'^(?P<slug>[^/]+)/popup/$', views.location_detail_popup, name='location-detail-popup'),
]

myproject/urls.py
# myproject/urls.py
# -*- coding: UTF-8 -*-
from __future__ import unicode_literals
from django.conf.urls import include, url
# from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views
from django.core.urlresolvers import reverse_lazy
from django.utils.translation import string_concat
from django.utils.translation import ugettext_lazy as _
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

from crispy_forms.helper import FormHelper
from crispy_forms import layout, bootstrap
from haystack.views import SearchView
import utils.views

# commented out bulletin_board and tastypie
# from tastypie.api import Api
# from bulletin_board.api import CategoryResource, BulletinResource
# from bulletin_board.views import RESTBulletinList, RESTBulletinDetail

admin.autodiscover()
admin.site.site_header = "MyProject administration"
admin.site.site_title = "MyAdmin Portal"
admin.site.index_title = "Welcome to MyProject"

# v1_api = Api(api_name="v1")
# v1_api.register(CategoryResource())
# v1_api.register(BulletinResource())

login_helper = FormHelper()
login_helper.form_action = reverse_lazy("my_login_page")
login_helper.form_method = "POST"
login_helper.form_class = "form-signin"
login_helper.html5_required = True
login_helper.layout = layout.Layout(layout.HTML(
    string_concat("""<h2 class="form-signinheading">""", "(Please Sign In)", """</h2>""")),
    layout.Field("username", placeholder=_("username")),
    layout.Field("password", placeholder=_("password")),
    layout.HTML("""<input type="hidden" name="next" value="{{ next }}" />"""),
    layout.Submit("submit", _("Login"), css_class="btn-lg"),
)


class CrispySearchView(SearchView):
    def extra_context(self):
        helper = FormHelper()
        helper.form_tag = False
        helper.disable_csrf = True
        return {"search_helper": helper}


urlpatterns = i18n_patterns(
    # Examples:
    # url(r'^$', myproject.views.home, name='home'),
    # url(r'^blog/', include('blog.urls')),
    # Comment out movies, to be included in djangoCMS
    # url(r'^movies/', include('movies.urls', namespace='movies')),
    url(r'^admin/', admin.site.urls),
    # Commented out, was blocking proper url-config
    # url(r'^', include('cms.urls')),
    url(r'login/$', views.LoginView.as_view(),
        {"extra_context": {"login_helper": login_helper}},
        name='my_login_page'
        ),
    url(r'^myapp1/', include('myapp1.urls', namespace='myapp1')),
    url(r'^quotes/', include('quotes.urls', namespace='quotes')),
    url(r'^likes/', include('likes.urls')),
    url(r'^locations/', include('locations.urls', namespace='locations')),
    url(r'^search/', CrispySearchView(), name='haystack_search'),
    url(r'^js-settings/$', utils.views.render_js,
        {"template_name": "settings.js"},
        name='js_settings'
        ),
    # Have to solve some tastypie errors
    # url(r'^bulletin/', include('bulletin_board.urls', namespace='bulletin')),
    # url(r'^api/', include('v1_api.urls')),

    url(r"^api-auth/",
        include("rest_framework.urls",
                namespace="rest_framework")
        ),
    # Affected by commenting out bulletin_board
    # url(r"^rest-api/bulletin-board/$",
    #     RESTBulletinList.as_view(),
    #     name="rest_bulletin_list"
    #     ),
    # url(r"^rest-api/bulletin-board/(?P<pk>[0-9]+)/$",
    #     RESTBulletinDetail.as_view(),
    #     name="rest_bulletin_detail"
    #     ),
)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static( settings.STATIC_URL, document_root=settings.STATIC_ROOT )
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

locations/models.py
# locations/models.py
# -*- coding: UTF-8 -*-
from __future__ import unicode_literals
import os
from django.db import models
from django.utils.timezone import now as timezone_now
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import python_2_unicode_compatible


COUNTRY_CHOICES = (
    ("UG", _("Uganda")),
    ("KE", _("Kenya")),
    ("RW", _("Rwanda")),
    ("TZ", _("Tanzania")),
)


def upload_to(instance, filename):
    """
    This upload_to() function, sets the path of the uploaded picture
    to be something similar to location/201504/20150424140000.png.
    As you can see, we use the date timestamp as the filename to ensure its uniqueness.
    We pass this function to the *_image field.
    - Instance is a positional argument to help load more than one image
    """
    now = timezone_now()
    """
    os.path.splitext(path) - splits the pathname path into a pair (root, ext) such that 
    root + ext == path, (ext is empty or begins with a period and contains at most one period).
    Leading periods on the basename are ignored; splitext('.js') returns ('.js', '').
    """
    filename_base, filename_ext = os.path.splitext(filename)
    return "location/%s%s" % (now.strftime("%Y%m/%Y%m%d%H%M%S"), filename_ext.lower(), )


@python_2_unicode_compatible
class Location(models.Model):
    title = models.CharField(_("Title"), max_length=200)
    slug = models.SlugField(help_text="A short label, generally used in URLs.")
    description = models.TextField(_("description"), blank=True)
    street_address = models.CharField(_("street address"), max_length=255, blank=True)
    village = models.CharField(_("village"), max_length=255, blank=True)
    postal_code = models.CharField(_("postal code"), max_length=10, blank=True)
    city = models.CharField(_("city"), max_length=255, blank=True)
    country = models.CharField(
        _("country"),
        max_length=2, blank=True,
        choices=COUNTRY_CHOICES
    )
    small_image = models.ImageField(
        _("Small Image"),
        upload_to=upload_to,
        blank=True, null=True
    )
    medium_image = models.ImageField(
        _("Medium Image"),
        upload_to=upload_to,
        blank=True, null=True
    )
    large_image = models.ImageField(
        _("Large Image"),
        upload_to=upload_to,
        blank=True, null=True
    )
    latitude = models.FloatField(
        _("latitude"),
        help_text=_("Latitude (Lat.) is the angle between any point and the equator "
                    "(north pole is at 90; south pole is at -90)."),
        blank=True, null=True
    )
    longitude = models.FloatField(
        _("longitude"),
        help_text=_("Longitude (Long.) is the angle east or west of "
                    "an arbitrary point on Earth from Greenwich (UK), "
                    "which is the international zero-longitude point "
                    "(longitude=0 degrees). "
                    "The anti-meridian of Greenwich is both 180 "
                    "(direction to east) and -180 (direction to west)."),
        blank=True, null=True
    )

    class Meta:
        verbose_name = _("Location")
        verbose_name_plural = _("Locations")

    def __str__(self):
        return self.title

myproject/models.py
# models.py
# -*- coding: UTF-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import python_2_unicode_compatible


@python_2_unicode_compatible
class NewsArticle(models.Model):
    title = models.CharField(_("Title"), max_length=200)
    content = models.TextField(_("Content"))

    class Meta:
        verbose_name = _("News Article")
        verbose_name_plural = _("News Articles")

    def __str__(self):
        return self.title

locations/views.py
# locations/views.py
# -*- coding: UTF-8 -*-
from __future__ import unicode_literals

from django.shortcuts import get_object_or_404, render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from locations.models import Location


class LocationListView(ListView):
    model = Location
    context_object_name = 'location_list'
    template_name = 'locations/location_list.html'


class LocationDetailView(DetailView):
    model = Location
    template_name = 'locations/location_detail.html'


def location_detail_popup(request, slug):
    location = get_object_or_404(Location, slug=slug)
    return render(request,
                  "locations/location_detail_popup.html",
                  {"location": location}
                  )

myproject/templates/locations/location_detail.html
{# templates/locations/location_detail.html #}
{% extends "base.html" %}
{% load i18n likes_tags %}

{% block title %}{{ location.title }}{% endblock title %}
{% block header %}{{ location.title|escape }}{% endblock header %}

{% block content %}
    {% if request.user.is_authenticated %}
        {% like_widget for location %}
    {% endif %}
    <img class="img-full-width"
         src="{{ location.small_image.url }}"
         data-small-src="{{ location.small_image.url }}"
         data-medium-src="{{ location.medium_image.url }}"
         data-large-src="{{ location.large_image.url }}"
         alt="{{ location.title|escape }}"
      />
    <div id="map"
         data-latitude="{{ location.latitude|stringformat:'f' }}"
         data-longitude="{{ location.longitude|stringformat:'f' }}">
       </div>
{% endblock content %}

{% block extrabody %}
    <script src="https://maps-api-ssl.google.com/maps/api/js?v=3"></script>
    <script src="{{ STATIC_URL }}site/js/location_detail.js"></script>
    <script src="{{ STATIC_URL }}site/js/likes.js"></script>
{% endblock extrabody %}

myproject/templates/locations/location_detail_popup.html
{# templates/locations/location_detail_popup.html #}
{% load i18n %}

<p><img src="{{ location.small_image.url }}" alt="{{ location.title|escape }}" />
    </p>
<p class="clearfix">
    <a href="{% url 'locations:location-detail' slug=location.slug %}"
        class="btn btn-default pull-right">
        {% trans "More" %}
        <i class="material-icons align-text-bottom">&#xe5cc;</i>
    </a>
    </p>

myproject/templates/locations/location_list.html
{# templates/locations/location_list.html #}
{% extends "base.html" %}

{% block content %}
    {% if location_list %}
        <ul>
            {% for location in location_list %}
            <!--<li>
                <a href="{#% url 'locations:location-detail' slug=location.slug %#}">
                    {#{ location.title }#}
                </a>
            </li>-->
            <li class="item">
                <a href="{% url 'locations:location-detail' slug=location.slug %}"
                    data-popup-url="{% url 'locations:location-detail-popup' slug=location.slug %}"
                    data-popup-title="{{ location.title|escape }}">
                    {{ location.title }}
                </a>
            </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Oops!! You have no locations yet.</p>
    {% endif %}
{% endblock content %}
{% block extrabody %}
<div id="popup" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"
                        aria-hidden="true">
                    <i class="material-icons md-18">&#xe5c9;</i>
                </button>
                <h4 class="modal-title">Modal title</h4>
            </div>
            <div class="modal-body"></div>
        </div>
    </div>
</div>
<script src="{{ STATIC_URL }}site/js/location_list.js"></script>
{% endblock extrabody %}