cv/urls.py
# cv/urls.py
# -*- coding: UTF-8 -*-
from __future__ import unicode_literals
from django.conf.urls import patterns, url


urlpatterns = patterns('cv.views',
	url(r'^(?P<cv_id>\d+)/pdf/$', "download_cv_pdf", name="download_cv_pdf"),
)

myproject/urls.py
# myproject/urls.py
# -*- coding: UTF-8 -*-
from __future__ import unicode_literals
from django.conf.urls import include, url
# from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views
from django.core.urlresolvers import reverse_lazy
from django.utils.translation import string_concat
from django.utils.translation import ugettext_lazy as _
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

from crispy_forms.helper import FormHelper
from crispy_forms import layout, bootstrap
from haystack.views import SearchView
import utils.views

# commented out bulletin_board and tastypie
# from tastypie.api import Api
# from bulletin_board.api import CategoryResource, BulletinResource
# from bulletin_board.views import RESTBulletinList, RESTBulletinDetail

admin.autodiscover()
admin.site.site_header = "MyProject administration"
admin.site.site_title = "MyAdmin Portal"
admin.site.index_title = "Welcome to MyProject"

# v1_api = Api(api_name="v1")
# v1_api.register(CategoryResource())
# v1_api.register(BulletinResource())

login_helper = FormHelper()
login_helper.form_action = reverse_lazy("my_login_page")
login_helper.form_method = "POST"
login_helper.form_class = "form-signin"
login_helper.html5_required = True
login_helper.layout = layout.Layout(layout.HTML(
    string_concat("""<h2 class="form-signinheading">""", "(Please Sign In)", """</h2>""")),
    layout.Field("username", placeholder=_("username")),
    layout.Field("password", placeholder=_("password")),
    layout.HTML("""<input type="hidden" name="next" value="{{ next }}" />"""),
    layout.Submit("submit", _("Login"), css_class="btn-lg"),
)


class CrispySearchView(SearchView):
    def extra_context(self):
        helper = FormHelper()
        helper.form_tag = False
        helper.disable_csrf = True
        return {"search_helper": helper}


urlpatterns = i18n_patterns(
    # Examples:
    # url(r'^$', myproject.views.home, name='home'),
    # url(r'^blog/', include('blog.urls')),
    # Comment out movies, to be included in djangoCMS
    # url(r'^movies/', include('movies.urls', namespace='movies')),
    url(r'^admin/', admin.site.urls),
    # Commented out, was blocking proper url-config
    # url(r'^', include('cms.urls')),
    url(r'login/$', views.LoginView.as_view(),
        {"extra_context": {"login_helper": login_helper}},
        name='my_login_page'
        ),
    url(r'^myapp1/', include('myapp1.urls', namespace='myapp1')),
    url(r'^quotes/', include('quotes.urls', namespace='quotes')),
    url(r'^likes/', include('likes.urls')),
    url(r'^locations/', include('locations.urls', namespace='locations')),
    url(r'^search/', CrispySearchView(), name='haystack_search'),
    url(r'^js-settings/$', utils.views.render_js,
        {"template_name": "settings.js"},
        name='js_settings'
        ),
    # Have to solve some tastypie errors
    # url(r'^bulletin/', include('bulletin_board.urls', namespace='bulletin')),
    # url(r'^api/', include('v1_api.urls')),

    url(r"^api-auth/",
        include("rest_framework.urls",
                namespace="rest_framework")
        ),
    # Affected by commenting out bulletin_board
    # url(r"^rest-api/bulletin-board/$",
    #     RESTBulletinList.as_view(),
    #     name="rest_bulletin_list"
    #     ),
    # url(r"^rest-api/bulletin-board/(?P<pk>[0-9]+)/$",
    #     RESTBulletinDetail.as_view(),
    #     name="rest_bulletin_detail"
    #     ),
)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static( settings.STATIC_URL, document_root=settings.STATIC_ROOT )
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cv/models.py
# cv/models.py
# -*- coding: UTF-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import python_2_unicode_compatible


@python_2_unicode_compatible
class CV(models.Model):
	first_name = models.CharField(_("First name"), max_length=40)
	last_name = models.CharField(_("Last name"), max_length=40)
	email = models.EmailField(_("Email"))
	
	def __str__(self):
		return self.first_name + " " + self.last_name


@python_2_unicode_compatible
class Experience(models.Model):
	cv = models.ForeignKey(CV)
	from_date = models.DateField(_("From"))
	till_date = models.DateField(_("Till"), null=True, blank=True)
	company = models.CharField(_("Company"), max_length=100)
	position = models.CharField(_("Position"), max_length=100)
	skills = models.TextField(_("Skills gained"), blank=True)
	
	def __str__(self):
		till = _("present")
		if self.till_date:
			till = self.till_date.strftime("%m/%Y")
		return _("%(from)s-%(till)s %(pos)s at %(company)s") % {
			"from": self.from_date.strftime("%m/%Y"),
			"till": till,
			"pos": self.position,
			"company": self.company,
		}
	
	class Meta:
		ordering = ("-from_date",)

myproject/models.py
# models.py
# -*- coding: UTF-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import python_2_unicode_compatible


@python_2_unicode_compatible
class NewsArticle(models.Model):
    title = models.CharField(_("Title"), max_length=200)
    content = models.TextField(_("Content"))

    class Meta:
        verbose_name = _("News Article")
        verbose_name_plural = _("News Articles")

    def __str__(self):
        return self.title

cv/views.py
# cv/views.py
# -*- coding: UTF-8 -*-
from __future__ import unicode_literals
try:
    from cStringIO import StringIO
except ImportError:
    from StringIO import StringIO
from xhtml2pdf import pisa
from django.conf import settings
from django.shortcuts import render, get_object_or_404
from django.template.loader import render_to_string
from django.http import HttpResponse
from .models import CV


def download_cv_pdf(request, cv_id):
	cv = get_object_or_404(CV, pk=cv_id)
	
	response = HttpResponse(content_type="application/pdf")
	response["Content-Disposition"] = "attachment; filename=%s_%s.pdf" % ( cv.first_name, cv.last_name )
	
	html = render_to_string("cv/cv_pdf.html", { "cv": cv,
		"MEDIA_ROOT": settings.MEDIA_ROOT,
		"STATIC_ROOT": settings.STATIC_ROOT,
	})
	pdf = pisa.pisaDocument(
		StringIO(html.encode("UTF-8")),
		response,
		encoding="UTF-8",
	)
	
	return response

myproject/templates/cv/cv_pdf.html
{# templates/cv/cv_pdf.html #}
<!DOCTYPE HTML>
<html>
<head>
   <meta charset="utf-8" />
   <title>My Title</title>
      <style type="text/css">
         @page {
            size: "A4";
            margin: 2.5cm 1.5cm 2.5cm 1.5cm;
            @frame footer {
               -pdf-frame-content: footerContent;
               bottom: 0cm;
               margin-left: 0cm;
               margin-right: 0cm;
               height: 1cm;
            }
         }
         #footerContent {
            color: #666;
            font-size: 10pt;
            text-align: center;
         }
      </style>
</head>
<body>
   <div>
      <h1>Curriculum Vitae</h1>
         <table>
            <tr>
               <td>
                  <p><b>{{ cv.first_name }} {{ cv.last_name }}</b>
                     <br/>
                     Contact: {{ cv.email }}
                  </p>
               </td>
               <td align="right">
                  <img src="{{ STATIC_ROOT }} /site/img/smiley.jpg" width="100" height="100" />
               </td>
            </tr>
         </table>
      <h2>Experience</h2>
         <table>
            {% for experience in cv.experience_set.all %}
             <tr>
                <td valign="top">
                   <p>{{ experience.from_date|date:"F Y" }} - 
                      {% if experience.till_date %}
                         {{ experience.till_date|date:"F Y" }}
                      {% else %}
                         present
                      {% endif %}
                       <br/>
                      {{ experience.position }} at {{ experience.company }}
                   </p>
                </td>
                <td valign="top">
                   <p><b>Skills gained</b>
                      <br/>
                      {{ experience.skills|linebreaksbr }}
                      <br/>
                      <br/>
                   </p>
                </td>
             </tr>
            {% endfor %}
         </table>
   </div>
   <pdf:nextpage>
   <div>
      This is an empty page to make a paper plane.
   </div>
   <div id="footerContent">
      Document generated at {% now "Y-m-d" %} | Page <pdf:pagenumber> of <pdf:pagecount>
   </div>
</body>
</html>